version: '3.7'
services:
  db:
    image: postgres:latest
    container_name: mydb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: master
      POSTGRES_PASSWORD: rootpw
      POSTGRES_DB: develop
